replicaCount: 1

image:
  repository: postgres
  tag: "13"
  pullPolicy: IfNotPresent

postgresql:
  username: appuser
  password: changeme
  database: appdb
  replication:
    enabled: false

persistence:
  enabled: true
  size: 8Gi
  storageClass: standard
